title: VJ Sairam # your name (or website title) here
logo: "/images/image.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  DevOps Engineer - 9+ years' of experience 
  <br><br>
  <a href="https://www.linkedin.com/in/vjsr/">View My LinkedIn Profile</a> <br>
  <a href="https://www.skillshare.com/classes/Helm-The-Kubernetes-Package-Manager-1-Hr-Crash-Course/793852755">View My Helm Course</a> <br/>
  <a href="https://www.skillshare.com/classes/AWS-Serverless-Application-Model-SAM-1-Hr-Crash-Course/1829212456">View My AWS SAM Course</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
